<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta name="description" content="<?php echo $this->description ?>">
        <title>Cast</title>

        <link href="/resources/favicon.ico" rel="shortcut icon" />

        <link href="/resources/js/extjs/4.1.1/resources/css/ext-all.css" rel="stylesheet" />
        <link href="/resources/css/main.css" rel="stylesheet" />

        <?php if ($this->debug): ?>
        <script type="text/javascript" src="/resources/js/extjs/4.1.1/ext-all-debug.js"></script>
        <?php else: ?>
        <script type="text/javascript" src="/resources/js/extjs/4.1.1/ext-all.js"></script>
        <?php endif; ?>
        <script type="text/javascript" src="/resources/js/extjs/4.1.1/locale/ext-lang-ja.js"></script>

        <script type="text/javascript">
            Ext.ns('CAST');
            CAST = {};
        </script>

        <script type="text/javascript" src="/resources/js/cast/locale/cast-locale-ja.js"></script>
        <script type="text/javascript" src="/resources/js/cast/API.js"></script>
        <script type="text/javascript">
            Ext.direct.Manager.addProvider(CAST.REMOTING_API);
        </script>            

        <?php if ($this->debug): ?>
        <script type="text/javascript" src="/src/app/Events.js"></script>
        <script type="text/javascript" src="/src/app/Controllers.js"></script>
        <script type="text/javascript" src="/ct/app.js"></script>
        <?php else: ?>
        <script type="text/javascript" src="/resources/js/cast/app.js"></script>
        <?php endif; ?>
    </head>
    <body>
    
        <?php echo $this->layout()->content ?>

    </body>
</html>
